apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/THLfi/koronavilkku-backend.git
  labels:
    app: koronavilkku
    app.kubernetes.io/component: publish-token
    app.kubernetes.io/instance: publish-token
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: koronavilkku
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: "11"
  name: publish-token
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: publish-token:latest
  runPolicy: Serial
  source:
    contextDir: /publish-token
    git:
      uri: https://github.com/THLfi/koronavilkku-backend.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:11
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: publish-token-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: publish-token-github-webhook-secret
    type: GitHub
  - imageChange:
    type: ImageChange
  - type: ConfigChange
